In [ ]:
# Permet de tout executer au lancement du notebook + conserver le notebook actif pendant 2h
from IPython.display import Javascript
import sys
if ".." not in sys.path:
    sys.path.append("..")
from masquer import *
Javascript("""
function repeter(){
IPython.notebook.kernel.execute("a=1");
}
// execute a = 1 en python toutes les 8 minutes pendant 2h
let timerId = setInterval(() => repeter(), 4800);
setTimeout(() => { clearInterval(timerId); alert('fin de cession'); }, 7200000);

// Supprimer la taille limite pour la sortie d'une cellule
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
};
IPython.notebook.kernel.execute("url = '" + window.location + "'");

// Exécuter toutes les cellule du notebook
    require(
        ['base/js/namespace', 'jquery'], 
        function(jupyter, $) {
            
                
                jupyter.actions.call('jupyter-notebook:run-all-cells-below');
                jupyter.actions.call('jupyter-notebook:save-notebook');
                Jupyter.actions.call('jupyter-notebook:hide-header')

        }
    );""")

In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
HTML("""<style>
h1 {
  font-family: 'Permanent Marker', cursive;
  text-align: center;
  color: red;
  
}
ol {
  list-style-position: inside;
  margin-left: 1em;
  list-style-position: outside;
}
h2 {
  font-family: 'Permanent Marker', cursive;
  color: blue;
}
h3 {
  font-family: 'Permanent Marker', cursive;

}
</style>""")

# TD_08_4 - Entrainement

On peut aussi utiliser la base de données présente localement en utilisant la bibliothèque **sqlite3** de python. La requête SQL est alors envoyée sous forme d'une chaine de caractères

In [ ]:
import sqlite3
base_seconde = sqlite3.connect("seconde.sqlite3")
seconde = base_seconde.cursor()

L’énoncé de cet exercice utilise les mots du langage SQL suivant :  

SELECT, FROM, WHERE, JOIN, INSERT INTO, VALUES, COUNT, ORDER BY.  

Dans un lycée imaginaire, les données relatives aux élèves de secondes sont regroupées dans un fichier nommé
eleves_s0.csv. Un extrait de son contenu est représenté figure 1.

In [ ]:
import pandas
pandas.read_csv('eleves_s0.csv',sep=";")

Pour les besoins de l’organisation du lycée, le chef d’établissement exploite la base de données par des requêtes
en langage SQL. Il a pour cela créé une table (ou relation) SQL dénommée seconde dans son système de
gestion de bases de données dont la structure est la suivante :

In [ ]:
for row in seconde.execute("PRAGMA table_info(seconde);"):
    print(row)

num_eleve est la clé primaire de cette table.

## Question 1

1. Dans le modèle relationnel, quel est l’intérêt de l’attribut num_eleve.
2. Écrire une requête SQL d’insertion permettant d’enregistrer l’élève ACHIR Mussa dans la table
seconde. Les informations relatives à cet élève sont données dans la ligne 1 du fichier eleves_s0.csv
3. Lors de l’insertion de l’élève ALTMEYER Yohan (ligne 2 du fichier seconde_lyc.csv), une erreur de
saisie a été commise sur la première langue, qui devrait être allemand. Écrire une requête SQL de
mise à jour corrigeant les données de cet élève.

Question 1.
Le modèle relationnel est une manière de modéliser les relations existantes entre plusieurs informations, et de les ordonner entre elles. l'intérêt ici de l'attribut num_eleve est de pouvoir selectionner une case en utilisant les numéros d'eleve et non pas leur nom. C'est la clé primaire de la relation.

In [ ]:
#Question 2.
for row in seconde.execute("""INSERT INTO seconde
(num_eleve,nom,prenom,datenaissance,langue1,lanque2,option,classe)
VALUES(1333310FE,'ACHIR','MUSSA',01/01/2005,'anglais','espagnol','NaN','2A')""")
print(row)SELECT num_eleve FROM seconde

In [ ]:
#Question 3.
for row in seconde.execute("""UPDATE seconde
SET note = 2
WHERE num_eleve = 156929JJ""")
print(row)SELECT num_eleve FROM seconde

On suppose maintenant que la table seconde contient les informations issues de la figure 1 (ni
plus, ni moins, même si la figure 1 n’est qu’un extrait du fichier eleves_S0.csv).
1. Quel est le résultat de la requête
```SQL
SELECT num_eleve FROM seconde ;
```
2. On rappelle qu’en SQL, la fonction d’agrégation COUNT() permet de compter le nombre d’enregistrements dans une table. Quel est le résultat de la requête
```SQL
SELECT COUNT(num_eleve) FROM seconde ;
```
3. Écrire la requête permettant de connaître le nombre d’élèves qui font allemand en langue1 ou langue2.

Question 1.
Cette requête va renvoier tout les numêros d'élèves (num_eleve) de la table de seconde, comme par exemple le numéro d'élève de Mussa Achir qui correspond à 1333310FE.

Question 2.
Cette requête va renvoier le nombre de lignes qui possédent un num_eleve, soit 30 dans notre cas.

In [ ]:
for row in seconde.execute(SELECT COUNT num_eleve FROM seconde
                           WHERE langue1 = "allemand" OR langue2 = "allemand";):
    print(row)SELECT num_eleve FROM seconde

## Question 3

Le chef d’établissement souhaite faire évoluer la structure de sa base de données. Pour ce faire,
il créé une nouvelle table eleve dont la structure est la suivante :

In [ ]:
for row in seconde.execute("PRAGMA table_info(eleve)";):
    print(row)

Là encore, l’attribut num_eleve est un entier, les autres sont des chaines de caractère (le type CHAR).
1. Expliquer ce qu’apporte l’information clef étrangère pour l’attribur num_eleve de cette table
en termes d’intégrité et de cohérence.
2. On suppose la table eleve correctement créée et complétée. Le chef d’établissement aimerait lister
les élèves (nom, prénom, date de naissance) de la classe 2A.
Écrire la commande qui permet d’établir cette liste à l’aide d’une jointure entre eleve et seconde.

Question 1.
Cela permet de faire référence à des informations précedemment définies dans un tableau externe pour éviter de se répéter et de s'enmeler les pinceaux.

In [ ]:
for row in seconde.execute(SELECT nom, prenom, datenaissance FROM eleve
                           JOIN seconde ON eleve.num_eleve = seconde.num_eleve
                           WHERE seconde.classe = "2A";):
    print(row)

## Question 4

Proposer la structure d’une table coordonnees dans laquelle on pourra indiquer, pour chaque
élève, son adresse, son code postal, sa ville, son adresse mail. Préciser la clef primaire et/ou la clé
étrangère en vue de la mise en relation avec les autres tables.

In [ ]:
for row in seconde.execute(CREATE TABLE coordonnees
(num_eleve INT, adresse TEXT, code_postal TEXT, ville TEXT, mail TEXT;)
""")